Update install.md to add Docker install instructions
kinode-dao/kinode-book pull request #156
Opened 2024-04-04 18:04 UTC by 0xlynett

https://github.com/kinode-dao/kinode/pull/299

2024-04-04 20:40 UTC, nick1udwig requested changes
Style comment: please add some newlines to follow our convention having one sentence per line to make maintenance easier (e.g. prose diffs in PRs are much more readable w/ one sentence per line).

I want to add some discussion of common permutations users who are less familiar with Docker will probably want to know how to do, e.g.
1. Run multiple nodes (i.e. how to do port mapping properly & how to set up/use multiple volumes),
2. Copying native home dir in/out of volumes.

I'm sure there will be others. Anyways, you don't have to add this here if you don't want; I can follow up and add it.

The other thing I want to wait on before merging is testing on MacOS. I'm updating a machine now to test on. Then we can decide whether to "fully recommend" Docker or whether we should still mainly recommend using native binaries with Docker as a secondary suggestion.

2024-04-04 22:19 UTC, nick1udwig approved these changes
Overall comment: please add newlines between sentences so that each sentence is on its own line.

Other than that, I left some more specific comments. Please address comments if they are all clear and then merge when ready.

Thanks for the PR! :rocket:

2024-04-04 22:19 UTC, nick1udwig commented on src/install.md
> +The recommended method for Linux users is to use a prebuilt Docker image. Other operating systems are not yet supported: use the binary instead.
Tested on macOS & it worked great. Change this first sentence to something like `... Linux and macOS users ...` and the second sentence to specifically say `Windows may work, but is not officially supported.`

2024-04-04 22:19 UTC, nick1udwig commented on src/install.md
> +First, install the Docker Engine. Instructions will be different depending on your distribution, but it is recommended to follow [the method outlined in the official Docker website.](https://docs.doc
Since it works for macOS as well, let's change this to be a little more general. Instead of `Docker Engine` we can say `Docker` and then we can change `distribution` to `OS` and add an additional link at the end for macOS: https://docs.docker.com/desktop/install/mac-install/

2024-04-04 22:19 UTC, nick1udwig commented on src/install.md
> +Make sure to perform any post-install necessary afterwards, such as adding your user to the `docker` group.
Let's note this is for Linux and add link https://docs.docker.com/engine/install/linux-postinstall/

2024-04-04 22:19 UTC, nick1udwig commented on src/install.md
> +The image expects a volume mounted at `/kinode`. This volume may be empty or may contain another Kinode's data. It will be used as the home directory of your Kinode.
typo: `/kinode` -> `/kinode-home`

Maybe also add a note that it is one volume per Kinode, so new identities will require new volumes; something to that effect.

2024-04-05 02:45 UTC, dr-frmr commented
Can merge after 1-sentence-per-line is done

2024-04-05 10:38 UTC, 0xlynett commented on src/install.md
> +First, install the Docker Engine. Instructions will be different depending on your distribution, but it is recommended to follow [the method outlined in the official Docker website.](https://docs.doc
gonna link to https://docs.docker.com/get-docker/ because it has instructions for linux, windows, and mac

2024-04-05 10:54 UTC, 0xlynett commented
added all the stuff you mentioned except copying native home dir in/out of a volume, due to my lack of experience with docker i'm not sure how to do that properly haha

2024-04-05 16:29 UTC, merged