add "write to eth" cookbook
kinode-dao/kinode-book pull request #165
Opened 2024-05-02 15:47 UTC by bitful-pannul

2024-05-07 21:36 UTC, dr-frmr approved these changes
LGTM!

2024-05-08 13:37 UTC, nick1udwig requested changes
Overall comment: style is to use `you`s and no `we`s or `let's`. I know it is quite natural to write prose like you do here, but we need to keep consistent style across the docs. Please rewrite to remove `we`s and `let's`.

2024-05-08 13:37 UTC, nick1udwig commented on src/cookbook/writing_data_to_eth.md
> +Now we boot a fakechain, either with `kit f` which boots one at port 8545 in the background, or manually with `anvil --load-state kinostate.json`.
Put lines that are for copy-pasting in between triple backtics. I.e. this line should probably read

Now we boot a fakechain, either with `kit f` which boots one at port 8545 in the background, or manually with 
```
anvil --load-state kinostate.json
```

2024-05-08 13:37 UTC, nick1udwig commented on src/cookbook/writing_data_to_eth.md
> +Then we can run `forge script --rpc-url http://localhost:8545 script/Deploy.s.sol --broadcast` we'll see a printout that looks something like this:
Same as above: to triple backtics.

2024-05-08 13:37 UTC, nick1udwig commented on src/cookbook/writing_data_to_eth.md
> +Pretty cool huh? We can now do things like define a setNumber() call just like this:
One sentence per line

2024-05-08 13:37 UTC, nick1udwig commented on src/cookbook/writing_data_to_eth.md
> +Now, we'll add the 2 writes that are possible: increment() and setNumber(newNumber). To do this, we'll need to define a wallet, and import a few new crates:
One sentence per line

2024-05-08 13:37 UTC, nick1udwig commented on src/cookbook/writing_data_to_eth.md
> +Nice! Putting it all together, we can build and start the package on a fake node (`kit f` if you don't have one running), `kit bs`.
One sentence per line

2024-05-10 23:42 UTC, merged