Section 4. and 4.X. Kit
kinode-dao/kinode-book pull request #186
Opened 2024-05-09 08:38 UTC by jurij-jukic

Section 4.1., Logging
1. 'Logs are printed to the screen and stored, by default, at /tmp/kinode-kit-cache/logs/log.log.'
- what does it mean that logs are printed to the screen?
2. 'The default logging level is `info`.'
- are the other logging levels explained somewhere?
3. 'These defaults can be changed by setting environment variables'
- might be good to have an example of an .env file

2024-05-09 09:29 UTC, jurij-jukic commented
Section 4.2.
1. 'Version of Kinode binary to use (overridden by --runtime-path) [default: latest] [possible values: latest, v0.5.3-alpha, v0.5.2-alpha, v0.5.1-alpha]'
- what are the latest versions which should be put here?
2. 'Fetch and run a specific version of the binary; defaults to most recent version (here, `0.5.0`).'
- what's the latest version which should be put here
3. '--network-router-port Run the fake node network router on this port; defaults to 9001. Additional fake nodes must point to the same port to connect to the fake node network.'
- this is for testing indirect nodes?
4. '--testnet Connect to the Sepolia testnet rather than the Optimism mainnet.'
- connects to Optimism on Sepolia correct?
5. '--persist'
- how do you boot a persisted node again after it was shut down? I assume with --home. example would be useful here
6. '--password The password of the fake node; defaults to secret.'
- is `secret` some type, or an actual password value?
7. '--verbosity Set the verbosity of the node; higher is more verbose; default is 0.'
- what are the acceptable values for verbosity? where is it specified?

Some curiosity about fake nodes (mostly informed by how they worked on urbit):
8. 'Though this lack of connectivity makes them easy to spin up and throw away, the downside is no access to services on the network, like remote LLMs.'
- i remember fakeships on urbit being able to connect to the internet, just not interface with the live urbit PKI. isnt sth like this desirable for fake nodes as well? so e.g. you could test your LLMs from a fake node

2024-05-09 11:10 UTC, jurij-jukic commented
Section 4.4. kit build
1. 'kit build builds each process in the package and places the .wasm binaries into the pkg/ directory for installation.'
- 'into the pkg/ directory for installation' - what does installation specifically mean here?
2. 'After compiling each process, it places the output .wasm binaries within the pkg/ directory at the top-level of the given package directory'
- is there an example folder tree somewhere which represents this?
3. having a separate `kit build-start-package` page might make sense because that command still has a bunch of parameters (even if they are covered separately in `kit build` and `kit start-package`) and people might want to refer to it
4. so far i've changed all aliases in examples to full cmds (i.e. `kit b --help` -> `kit build --help`), thought it would make it clearer, but now i'm not sure. it's probably useful to give an example of how to use aliases

2024-05-09 13:15 UTC, jurij-jukic commented
Section 4.6. kit remove-package
1. 'If passed an optional positional argument `DIR`( the path to a package directory), the `metadata.json` therein is parsed and that package is removed from the node.'
- why is it necessary to parse `metadata.json` here?

2024-05-09 15:29 UTC, nick1udwig commented
> Section 4.1. Installation; Logging
> 
> 1. 'Logs are printed to the screen and stored, by default, at /tmp/kinode-kit-cache/logs/log.log.'
> 
> * what does it mean that logs are printed to the screen?
> 
> 2. 'The default logging level is `info`.'
> 
> * are the other logging levels explained somewhere?
> 
> 3. 'These defaults can be changed by setting environment variables'
> 
> * might be good to have an example of an .env file

1. Like printed to the terminal screen.
2. No; maybe we should. Standard logging levels: `debug`, `info`, `warning`, `error`.
3. Hmm, its not obvious to me there's much to gain from doing so, but I also have never used a `.env`; I just set in terminal with `export`. What do you see as the benefit of adding a `.env`?

2024-05-09 15:42 UTC, nick1udwig commented
> Section 4.3. kit new
> 
> 1. 'You can create a variety of templates using kit new. Currently, three languages are supported: rust (the default), python, and javascript.'
> 
> * is it explained somewhere how apps in different language (in general) work? Would love to link to it. This discussion about wit seems relevant [Section 3. Process Standard Library #182](https://github.com/kinode-dao/kinode-book/pull/182), but I dont think that section is the best place to explain apps in different langs

Agreed section 3 is not the right place for the discussion -- that lib is specific to Rust.

Looks like we do not have such a document: https://book.kinode.org/?search=language

I agree we should add one, but I don't think we should do so right now. Although we technically support py & JS, it is a somewhat trivial level of support: to make it full-featured we really need to build out process libs in those langs. Could you open an issue?

2024-05-09 15:47 UTC, nick1udwig commented
> Section 4.4. kit build
> 
> 1. having a separate `kit build-start-package` page might make sense because that command still has a bunch of parameters (even if they are covered separately in `kit build` and `kit start-package`) and people might want to refer to it
> 2. so far i've changed all aliases in examples to full cmds (i.e. `kit b --help` -> `kit build --help`), thought it would make it clearer, but now i'm not sure. it's probably useful to give an example of how to use aliases

1. Sounds good, plz do add
2. Yeah, my intent was that these would illustrate the aliases through use ("I'm on build page and its showing `kit b`, oh I guess thats an alias"). If you think its unclear we can change it to the full ones

2024-05-09 15:51 UTC, jurij-jukic commented
Section 4.9. kit run-tests
1. 'Consider the following example, from [core tests]():'
- i cannot find the link for core tests.
- would prefer to link to that tests.toml file because it makes it incredibly clunky to read the page. I broke down each section with its corresponding example code
2. I removed the directory tree because i dont think it helps understanding and also makes the page really clunky to read
3. https://book.kinode.org/kit/run-tests.html#test-package-format
- is there a link where this interface is formally specified?

2024-05-09 16:30 UTC, nick1udwig requested changes
A few nits & rewordings

2024-05-09 16:30 UTC, nick1udwig commented on src/kit/install.md
> +You are encouraged to make use of the `--help` flag, which can be used for top-level `kit` commands:
What I was going for here is that you can use it like `kit --help` as well as like `kit new --help`, i.e. for the "top-level `kit`" as well as for the subcommands. Maybe we can say here

```
used for the top-level `kit` command:
```

?

2024-05-09 16:30 UTC, nick1udwig commented on src/kit/new.md
> +Two templates are currently supported: `chat`, a simple chat application; and `fibonacci`, which computes Fibonacci numbers.
I like the semicolon change. We do need to update this to either
1. list all four that we now offer (chat, echo, fib, file_transfer), or
2. just refer to the section below.

2024-05-09 16:30 UTC, nick1udwig commented on src/kit/new.md
> +The following table describes specifies whether a template "Exists/Has UI-enabled version" for each language/template combination:
nit: typo `describes specifies`
```
The following table describes specifies whether
```

2024-05-09 16:30 UTC, nick1udwig commented on src/kit/new.md
> +Directory where to create the template package.
This sentence isn't quite right. Maybe
```
Create template package in this directory.
```
?

2024-05-09 16:30 UTC, nick1udwig commented on src/kit/new.md
> +Currently have `chat`, a simple chat application; `echo`, an application that prints and responds with the received message; and `fibonacci`, a naive fibonacci-number-computer.
As mentioned above we should probably change this to just link to the table rather than maintaining list here. Maybe table section should have descriptors there as well.

2024-05-09 16:30 UTC, nick1udwig commented on src/kit/remove-package.md
> +If passed an optional positional argument `DIR` (the path to a package directory), the `metadata.json` therein is parsed to get the `packageID` and that package is removed from the node.
```
packageID
```
to
```
package_id
```

2024-05-09 16:36 UTC, nick1udwig commented
> Section 4.9. kit run-tests
> 
> 1. 'Consider the following example, from core tests:'
> 
> * i cannot find the link for core tests.
> * would prefer to link to that tests.toml file because it makes it incredibly clunky to read the page. I broke down each section with its corresponding example code
> 
> 2. I removed the directory tree because i dont think it helps understanding and also makes the page really clunky to read
> 3. https://book.kinode.org/kit/run-tests.html#test-package-format
> 
> * is there a link where this interface is formally specified?

1. https://github.com/kinode-dao/core_tests
2. Ok, will review
3. https://github.com/kinode-dao/kinode/blob/main/kinode/packages/tester/tester_types.rs#L18-L57

Interface will change with wit work I'm doing now, but that's where it lives for now.

2024-05-09 16:43 UTC, nick1udwig reviewed
A few more comments

2024-05-09 16:43 UTC, nick1udwig commented on src/kit/run-tests.md
> +We will be referring to `tests.toml` as an example, from [core tests]().
No `we` allowed; open to other wordings, but current convention is no `we`.

2024-05-09 16:43 UTC, nick1udwig commented on src/kit/run-tests.md
> +`is_testnet`        | Boolean        | Whether to connect to Optimism on Sepolia (`false` -> Optimism mainnet)
This field is old, please remove;

https://github.com/kinode-dao/kit/blob/master/src/run_tests/types.rs#L10-L46

2024-05-10 07:54 UTC, jurij-jukic commented
Re 4.1. kit installation

> * No; maybe we should. Standard logging levels: `debug`, `info`, `warning`, `error`.

Mentioned these. Even if they are not explained, I still think it's good to have them.

> Hmm, its not obvious to me there's much to gain from doing so, but I also have never used a .env; I just set in terminal with export. What do you see as the benefit of adding a .env?

That works too, just wanted an example of how to use. Added an `export` example.

2024-05-10 08:29 UTC, jurij-jukic commented
Re section 4.9. on tests
tests.toml snippets in the doc are outdated. (and prob some other stuff) should I wait for @bitful-pannul's work to finish before updating the doc, or no more changes will be made?

2024-05-10 08:35 UTC, jurij-jukic commented on src/kit/inject-message.md
> +It will forward the message from `fake.os`s HTTP server to `fake2@foo:foo:template.os`.
much better! thanks

2024-05-10 08:38 UTC, jurij-jukic commented on src/kit/install.md
> +You are encouraged to make use of the `--help` flag, which can be used for top-level `kit` commands:
yup, my blunder

2024-05-10 08:45 UTC, jurij-jukic commented on src/kit/new.md
> +Directory where to create the template package.
that works, thanks

2024-05-10 08:49 UTC, jurij-jukic commented on src/kit/new.md
> +Currently have `chat`, a simple chat application; `echo`, an application that prints and responds with the received message; and `fibonacci`, a naive fibonacci-number-computer.
wdym by 'descriptors'? like there should be a few sentences about each template describing it?

2024-05-10 09:49 UTC, jurij-jukic commented
Section 4.4. kit build
Added `--no-ui` option in kit build, it wasn't documented before

2024-05-10 16:51 UTC, nick1udwig commented
> Re section 4.9. on tests tests.toml snippets in the doc are outdated. (and prob some other stuff) should I wait for @bitful-pannul's work to finish before updating the doc, or no more changes will be made?

I think he will do a pass after this is merged.

2024-05-10 16:51 UTC, nick1udwig approved these changes
A couple comments, otherwise :rocket:

2024-05-10 16:51 UTC, nick1udwig commented on src/kit/install.md
> +The default logging level is `info`. Other logging levels are: `debug`, `warning` and `error`.
Please put one sentence per line.

2024-05-10 16:51 UTC, nick1udwig commented on .env
> +KIT_LOG_PATH=.
I think this file probably shouldn't be here?

2024-05-10 16:58 UTC, jurij-jukic commented on src/kit/install.md
> +The default logging level is `info`. Other logging levels are: `debug`, `warning` and `error`.
you patience is infinite :D

2024-05-10 17:03 UTC, jurij-jukic commented on src/kit/new.md
>  Language     | `chat`  | `echo` | `fibonacci` | `file_transfer`
one last thing - do you still want descriptors here? (also, still not sure exactly what you meant by that)

2024-05-10 18:48 UTC, dr-frmr approved these changes

2024-05-13 16:16 UTC, nick1udwig approved these changes
Looks good, thanks :+1:

2024-05-13 18:58 UTC, merged