kit chain
kinode-dao/kinode-book pull request #188
Opened 2024-05-09 22:52 UTC by bitful-pannul

2024-05-11 01:12 UTC, nick1udwig requested changes
Some comments; after @jurij-jukic s PRs we should also `grep -r` through the book for `.os` and change them all to `.dev`.

2024-05-11 01:12 UTC, nick1udwig commented on src/kit/boot-fake-node.md
> +It also boots a fake chain with anvil in the background (see [kit chain](../kit/chain.md)). This comes preseeded with KNS & app_store contracts, that fake nodes use to index each others networking in
1. let's link `anvil` to some relevant foundry anvil docs page
2. one sentence per line, please add newline
3. let's reword the second sentence in two ways:

First, change the opening `This` to `The fake chain` for more specificity. Second, let's reword the second half of the sentence. We need to say what KNS is used for AND what app_store is used for and make it clear to which we are referring.

2024-05-11 01:12 UTC, nick1udwig commented on src/kit/boot-fake-node.md
> +It also boots a fake chain with anvil in the background (see [kit chain](../kit/chain.md)). This comes preseeded with KNS & app_store contracts, that fake nodes use to index each others networking in
Possible rewording:
```
The fake chain comes preseeded with two contracts: KNS, which nodes use to index networking info of other nodes; and app_store, which _____
```

2024-05-11 01:12 UTC, nick1udwig commented on src/kit/boot-fake-node.md
> +For example, to start two fake nodes, `fakedev` and `fake2.dev`:
Missing a period

2024-05-11 01:12 UTC, nick1udwig commented on src/kit/chain.md
> +`kit chain` starts an anvil node with the arguments `--load-state kinostate.json`. This json file includes the [KNS](https://github.com/kinode-dao/KNS) & app_store contracts, and is included in the k
* One sentence per line
* kit should be `kit`

2024-05-11 01:12 UTC, nick1udwig commented on src/kit/chain.md
> +Note that while the kns_indexer and app_store apps in fake nodes use this chain to index events, any events loaded from a json statefile, aren't replayed upon restarting anvil. This is a future `foun
One sentence per line. If it really is a feature request, plz open an issue

2024-05-11 01:12 UTC, nick1udwig commented on src/kit/chain.md
> +Port to run anvil fakechain on. Defaults to `8545`.
One sentence per line

2024-05-11 01:12 UTC, nick1udwig commented on src/kit/chain.md
> +```
We probably should get rid of this ascii art

2024-05-16 01:22 UTC, bitful-pannul commented
> Some comments; after @jurij-jukic s PRs we should also `grep -r` through the book for `.os` and change them all to `.dev`.

Addressed, thank you! Regarding changing `.os` to `.dev` everywhere, I defaulted in kit to .dev to show the possibility of contract development, here in the case of a custom TLD contract. 

But it could just as well use the .os one, and perhaps it would be clearer if it did?

2024-05-16 01:31 UTC, nick1udwig approved these changes
all -> `.dev`; otherwise LGTM

2024-05-16 01:32 UTC, merged