Section 5: My First Kinode App
kinode-dao/kinode-book pull request #191
Opened 2024-05-10 11:27 UTC by jurij-jukic

1. Chapter 1 Environment Setup; Exploring the Package
- should something be said here about the second `Cargo.toml` file in `my_chat_app` root?
- should something be said about `scripts.json` separately? what exacly does script.json do?
- what exactly is `metadata.json` used for? to make the package an nft?
- 'As of 240118, only the Rust chat template has a UI-enabled version.' is '240118' a date?

2024-05-10 14:28 UTC, jurij-jukic commented
Chapter 2
1. 'In order to compile properly to the Kinode environment, every process must generate the WIT bindings for the process "world".'
- should we be explaining here what WIT bindings are ?
- what is "world" here? is it like a namespace of processes?

2. 'every process must define a Component struct'
- what is the Component struct? (and link pls)

3. i'm a bit confused in general with this tutorial. we are *not* building the same thing as 'my_chat_app' but a random app which only sends messages to itself? it would be much easier to read if i knew what the app was supposed to do from the beginning, and then every step of the way would have some context

2024-05-10 16:52 UTC, nick1udwig commented
I'll add a review once you've worked through the chapters: ping me here or in discord/tg when PR is ready for review

2024-05-13 13:14 UTC, jurij-jukic commented
Section 5.3

1. I moved 'aside: `on_exit`' from 5.2 to 5.3 because in 5.3 the process is actually exited from, so it makes sense to put it there

2. 'It's also critical to document the overall structure of the program along with message blobs and metadata used'
- document it where?

3. 'First, create a request that uses the new `body` type (and stop expecting a response):'
```rust
  Request::new()
      .target(&our)
      .body(MyBody::hello("hello world"))
      .send();
```
- why are we not using `expect_response()` anymore?
- why are we not using `unwrap()` anymore?

4. `m our@<your_process>:<your_package>:<your_publisher> '{"Hello": "hey there"}'`
- this code uses the `send` script afaict, which is found in the chat app example, but not in the echo_app example. what is the right way to solve this:
  - include the `send` script in all templates, or
  - rewrite the doc so it specifically works with chat template?

2024-05-13 16:34 UTC, nick1udwig commented
> Chapter 1 Environment Setup
> 
> 1. Exploring the Package Qs
> 
> * should we mention the 'send' folder?
> * should something be said here about the second `Cargo.toml` file in `my_chat_app` root?
> * should something be said about `scripts.json` separately? what exactly does script.json do?
> * what exactly is `metadata.json` used for? to make the package an nft?
> 
> 2. 'As of 240118, only the Rust chat template has a UI-enabled version.'
> 
> * is '240118' a date? why not just link to that `kit new` section to specify whether UI is enabled or not, so we have to change it only in one place.
>   e.g. we could say: 'To see all templates and their options, look here(add link).'


> send folder & scripts.json

Let's say that they are scripts and link to the scripts page: https://book.kinode.org/cookbook/writing_scripts.html

> should something be said here about the second `Cargo.toml` file in `my_chat_app` root?

@jaxs-ribs can you comment on the purpose of this `Cargo.toml` file?

> metadata.json

This is multipurpose. Yes, it is NFT metadata, but it is also used by the Kinode system, specifically the app_store: https://github.com/kinode-dao/kinode/blob/main/kinode/packages/app_store/app_store/src/types.rs#L406-L424

2. Yes, let's link

2024-05-13 17:02 UTC, nick1udwig commented
> Section 5.3
> 
> 1. I moved 'aside: `on_exit`' from 5.2 to 5.3 because in 5.3 the process is actually exited from, so it makes sense to put it there
> 2. 'It's also critical to document the overall structure of the program along with message blobs and metadata used'
> 
> * document it where?
> 
> 3. 'First, create a request that uses the new `body` type (and stop expecting a response):'
> 
> ```rust
>   Request::new()
>       .target(&our)
>       .body(MyBody::hello("hello world"))
>       .send();
> ```
> 
> * why are we not using `expect_response()` anymore?
> * why are we not using `unwrap()` anymore?
> 
> 4. `m our@<your_process>:<your_package>:<your_publisher> '{"Hello": "hey there"}'`
> 
> * this code uses the `send` script afaict, which is found in the chat app example, but not in the echo_app example. what is the right way to solve this:
>   
>   * include the `send` script in all templates, or
>   * rewrite the doc so it specifically works with chat template?

2. There was not a canonical place. There will soon be in the form of WIT apis. In the current system we just have one [wit file](https://github.com/kinode-dao/kinode-wit/blob/master/kinode.wit) for all processes. The work I'm doing now is to allow processes to define their own wit files -- the APIs for the process. It also adds infra for publishing and reading published APIs. So let's add documentation about that once that work is done and leave this as is for now.

3. Its not made clear in the text, but looking at the final code, its because the handling of a `Hello` is to just print the text in the Request -- no Response is sent. We `.unwrap()` to consume the `Result` and avoid our text editor yelling at us -- probably we should be `unwrap`ing in both cases; good catch.

4. We are using the `m` script here, which is packaged with the terminal, not the `chat` app's `send`. `m` is a general script to send an arbitrary JSON-formatted Request to an arbitrary process (on our node or another node -- note the fully-qualified address). `send` in the chat app is a shortcut: it will send a chat-specific Request to the chat app running on our node. No need for modification of docs!

See `send` usage here: https://github.com/kinode-dao/kit/blob/master/src/new/templates/rust/no-ui/chat/send/src/lib.rs#L36

See `m` usage here: https://github.com/kinode-dao/kinode/blob/main/kinode/packages/terminal/m/src/lib.rs#L21

Some other scripts included by default in terminal: https://github.com/kinode-dao/kinode/tree/main/kinode/packages/terminal

2024-05-14 10:09 UTC, jurij-jukic commented
Section 5.2. https://github.com/kinode-dao/kinode-book/pull/191#issuecomment-2108198996
1. I took some sentences verbatim from the WASM docs you sent, I hope that's okay. They are referenced at the beginning of that subsection.
2. Please proof read specifically the entire 'Starting from Scratch' subsection as I added a lot of WASM explanations there

2024-05-14 15:11 UTC, jurij-jukic commented
Section 5.5.
- First it says you can publish an app easily from App Store, and then it says that publishing through a GUI is not possible yet but will be soon. I assume the latter is a mistake
- Should the steps for publishing an app manually stay there or can they be removed?

2024-05-14 15:56 UTC, nick1udwig commented
> Section 5.5.
> 
> * First it says you can publish an app easily from App Store, and then it says that publishing through a GUI is not possible yet but will be soon. I assume the latter is a mistake
> * Should the steps for publishing an app manually stay there or can they be removed?

We're going to be doing some work on app store shortly, so let's put off changing this page till then.

2024-05-14 17:08 UTC, nick1udwig approved these changes
Really nice work here. The discussion of wit in section 2 is great. Left some comments, but feel free to merge after fixing.

One other thing to consider doing before merging is to change the file names from `chapter_x.md` to be descriptive of the page, as all the other page titles are. This will involve re-linking throughout the book, but is something we should do at some point.

2024-05-14 17:08 UTC, nick1udwig commented on src/my_first_app/chapter_4.md
> +Request::new().target(our).body(body.bytes).send().unwrap();
prefer using `::to()`

2024-05-14 17:08 UTC, nick1udwig commented on src/my_first_app/chapter_4.md
> +Putting it all together, you get a process which you can build and start, then use cURL to send 'Hello' and 'Goodbye' requests via HTTP PUTs!
replace single-quotes with backticks

2024-05-14 17:08 UTC, nick1udwig commented on src/my_first_app/chapter_4.md
> +    Request::new().target(our).body(body.bytes).send().unwrap();
use `::to()`

2024-05-15 07:27 UTC, jurij-jukic commented on src/my_first_app/chapter_1.md
> +Note that not all templates have a UI-enabled version. More details about templates can be found [here](../kit/new.html#existshas-ui-enabled-version).
i even 'cntrl+F'ed for these ... sorry

2024-05-15 09:38 UTC, jurij-jukic commented on src/my_first_app/chapter_2.md
> +They may be written in any WASM-compatible language — for Kinode they are written in Rust.
any reason you are linking specifically to `kit new` instead of the kit default/overview page?

2024-05-15 09:44 UTC, jurij-jukic commented on src/my_first_app/chapter_2.md
> +    .target(&our)
i have changed to `Request::new().target()` from all `Request::to()`.

as the tutorial was building up, it started from `Request::new()` and went to `Request::new().target()` which was pretty clear, and replacing that with `Request::to()` was confusing, I had to look it up.

if `Request::to()` is the right way to do it, i propose the following:
- first example: use `Request::new().target()`
- second example: use `Request::to()`, explain its equivalent to the previous
- all the examples onwatds: use `Request::to()`

2024-05-15 09:50 UTC, jurij-jukic commented on src/my_first_app/chapter_3.md
> +In this section, you will upgrade your app so that it can handle messages with more elaborate data typs such as `enum`s and `struct`s. Additionally, you will learn why and how to exit out of a proces
can we use  `...processes completing or crashing.` ? 'returning' feels weird to me here

2024-05-15 09:53 UTC, jurij-jukic commented on src/my_first_app/chapter_3.md
>  Some popular options are `bincode` and `serde_json`.
did you mean to spell out the link there?
I assume it should go like:
```
Some popular options are `bincode`, [`rmp_serde`](https://docs.rs/rmp-serde/latest/rmp_serde/), and `serde_json`.```

2024-05-15 15:17 UTC, nick1udwig commented on src/my_first_app/chapter_2.md
> +They may be written in any WASM-compatible language — for Kinode they are written in Rust.
I'm fine with linking default/overview page :+1:

2024-05-15 15:18 UTC, nick1udwig commented on src/my_first_app/chapter_2.md
> +    .target(&our)
That sounds great :+1:

2024-05-15 15:18 UTC, nick1udwig commented on src/my_first_app/chapter_3.md
> +In this section, you will upgrade your app so that it can handle messages with more elaborate data typs such as `enum`s and `struct`s. Additionally, you will learn why and how to exit out of a proces
Yup, that sounds good :+1:

2024-05-15 15:19 UTC, nick1udwig commented on src/my_first_app/chapter_3.md
>  Some popular options are `bincode` and `serde_json`.
Whoops. Yeah, it can be a link to crate or just the crate name. The protocol in MessagePack, but we use that crate specifically -- probably fine to use others (and certainly other langs have to use their own MessagePack lib).

2024-05-15 20:41 UTC, dr-frmr commented on src/my_first_app/chapter_1.md
> +`"grant_capabilities"`   | Array of Strings or Objects                                                                    | Strings are `ProcessIDs` to grant messaging capabilties to; Objects have a
`ProcessId` not `ProcessID`, also, make sure to keep the plural-s out of the backtics

2024-05-15 20:41 UTC, dr-frmr commented on src/my_first_app/chapter_1.md
> +As an aside: each process has a unique `processID`, used to address messages to that process, that looks like
`ProcessId`

2024-05-15 20:42 UTC, dr-frmr commented on src/my_first_app/chapter_1.md
> +You can read more about `processID`s [here](../process/processes.md#overview).
`ProcessId`

2024-05-15 20:42 UTC, dr-frmr commented on src/my_first_app/chapter_1.md
> +The `.dev` suffix is used for development nodes.
should say

The `.dev` suffix is used for development nodes, by convention.

2024-05-15 20:45 UTC, dr-frmr requested changes
Left some needed changes

2024-05-15 20:45 UTC, dr-frmr commented on src/my_first_app/chapter_3.md
> +# Messaging with Larger Data Types
I would prefer to say "More Complex" rather than "Larger", as the latter implies large size in terms of bytes

2024-05-16 00:41 UTC, nick1udwig commented on src/my_first_app/chapter_1.md
> +The `.dev` suffix is used for development nodes.
So right now it is a technical requirement as well since only `.dev` nodes will be registered in the fake chain. I think this requirement will be loosened in the future? @bitful-pannul

2024-05-16 11:00 UTC, jurij-jukic commented
@nick1udwig please take a look at lines 172-173 in chapter 2.

as soon as that and the `.dev` thing are resolved, we can merge

2024-05-16 16:46 UTC, nick1udwig commented
Looks good :+1:

2024-05-17 19:43 UTC, bitful-pannul commented on src/my_first_app/chapter_1.md
> +The `.dev` suffix is used for development nodes.
Yes, can be loosened, the contract is there deployed, only change to make is in runtime parsing --fake-node-name argument and making the register tx to the other contract.

2024-05-20 10:43 UTC, merged